name: Check NVIDIA GPU Stock

on:
  schedule:
    - cron: '*/57 * * * *'  # Run every 57 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Restore cache
      id: cache-state
      uses: actions/cache@v4
      with:
        path: |
          gpu_availability.json
          .venv
          ~/.local
        key: gpu-state-${{ github.run_id }}
        restore-keys: |
          gpu-state-

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run stock checker
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM_NUMBER: ${{ vars.TWILIO_FROM_NUMBER }}
        TWILIO_MESSAGING_SERVICE_SID: ${{ secrets.TWILIO_MESSAGING_SERVICE_SID }}
      run: poetry run python main.py
